import { Inter } from "next/font/google";
import "./globals.css";
import Mainlayout from "@/components/Mainlayout";
import MenuContextProvider from "@/context/MenuContext";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MenuContextProvider>
          <Mainlayout>{children}</Mainlayout> 
        </MenuContextProvider>
      </body>
    </html>
  );
}
